# Travis continuous integration configuration file
matrix:
  include:
  - language: python
    python:
      - "3.7"
    dist: xenial
    install:
      - pip install -r requirements.txt
      - pip install codecov
    script:
      - pytest --cov=edx_xml_clean --cov-report=term-missing
    after_success:
      - codecov